# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CameraSetting_UI.ui'
#
# Created: Fri Mar  4 21:48:55 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(514, 742)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 501, 681))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.verticalLayoutWidget_2)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 491, 541))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.label_15 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_4.addWidget(self.label_15)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.brightness_horizontalSlider = QtGui.QSlider(self.horizontalLayoutWidget_2)
        self.brightness_horizontalSlider.setMaximum(255)
        self.brightness_horizontalSlider.setProperty("value", 128)
        self.brightness_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.brightness_horizontalSlider.setObjectName(_fromUtf8("brightness_horizontalSlider"))
        self.verticalLayout_3.addWidget(self.brightness_horizontalSlider)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.label_16 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_5.addWidget(self.label_16)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.contrast_horizontalSlider = QtGui.QSlider(self.horizontalLayoutWidget_2)
        self.contrast_horizontalSlider.setMaximum(255)
        self.contrast_horizontalSlider.setProperty("value", 128)
        self.contrast_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.contrast_horizontalSlider.setObjectName(_fromUtf8("contrast_horizontalSlider"))
        self.verticalLayout_3.addWidget(self.contrast_horizontalSlider)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.label_18 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_6.addWidget(self.label_18)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.saturation_horizontalSlider = QtGui.QSlider(self.horizontalLayoutWidget_2)
        self.saturation_horizontalSlider.setMaximum(255)
        self.saturation_horizontalSlider.setProperty("value", 128)
        self.saturation_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.saturation_horizontalSlider.setObjectName(_fromUtf8("saturation_horizontalSlider"))
        self.verticalLayout_3.addWidget(self.saturation_horizontalSlider)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_8.addWidget(self.label_4)
        self.label_20 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_8.addWidget(self.label_20)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.gain_horizontalSlider = QtGui.QSlider(self.horizontalLayoutWidget_2)
        self.gain_horizontalSlider.setMaximum(255)
        self.gain_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gain_horizontalSlider.setObjectName(_fromUtf8("gain_horizontalSlider"))
        self.verticalLayout_3.addWidget(self.gain_horizontalSlider)
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.power_line_frequency_comboBox = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.power_line_frequency_comboBox.setObjectName(_fromUtf8("power_line_frequency_comboBox"))
        self.power_line_frequency_comboBox.addItem(_fromUtf8(""))
        self.power_line_frequency_comboBox.addItem(_fromUtf8(""))
        self.power_line_frequency_comboBox.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.power_line_frequency_comboBox)
        self.white_balance_temperature_auto_checkBox = QtGui.QCheckBox(self.horizontalLayoutWidget_2)
        self.white_balance_temperature_auto_checkBox.setObjectName(_fromUtf8("white_balance_temperature_auto_checkBox"))
        self.verticalLayout_3.addWidget(self.white_balance_temperature_auto_checkBox)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_9.addWidget(self.label_6)
        self.label_21 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_9.addWidget(self.label_21)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.white_balance_temperature_horizontalSlider = QtGui.QSlider(self.horizontalLayoutWidget_2)
        self.white_balance_temperature_horizontalSlider.setMinimum(2000)
        self.white_balance_temperature_horizontalSlider.setMaximum(6500)
        self.white_balance_temperature_horizontalSlider.setProperty("value", 4000)
        self.white_balance_temperature_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.white_balance_temperature_horizontalSlider.setObjectName(_fromUtf8("white_balance_temperature_horizontalSlider"))
        self.verticalLayout_3.addWidget(self.white_balance_temperature_horizontalSlider)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_7 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_10.addWidget(self.label_7)
        self.label_22 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_10.addWidget(self.label_22)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.sharpness_horizontalSlider = QtGui.QSlider(self.horizontalLayoutWidget_2)
        self.sharpness_horizontalSlider.setMaximum(255)
        self.sharpness_horizontalSlider.setProperty("value", 128)
        self.sharpness_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sharpness_horizontalSlider.setObjectName(_fromUtf8("sharpness_horizontalSlider"))
        self.verticalLayout_3.addWidget(self.sharpness_horizontalSlider)
        self.load_camera_setting_pushButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.load_camera_setting_pushButton.setObjectName(_fromUtf8("load_camera_setting_pushButton"))
        self.verticalLayout_3.addWidget(self.load_camera_setting_pushButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_8 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_11.addWidget(self.label_8)
        self.label_23 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_11.addWidget(self.label_23)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.backlight_compensation_horizontalSlider = QtGui.QSlider(self.horizontalLayoutWidget_2)
        self.backlight_compensation_horizontalSlider.setMaximum(1)
        self.backlight_compensation_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.backlight_compensation_horizontalSlider.setObjectName(_fromUtf8("backlight_compensation_horizontalSlider"))
        self.verticalLayout_5.addWidget(self.backlight_compensation_horizontalSlider)
        self.label_9 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_5.addWidget(self.label_9)
        self.exposure_auto_comboBox = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.exposure_auto_comboBox.setObjectName(_fromUtf8("exposure_auto_comboBox"))
        self.exposure_auto_comboBox.addItem(_fromUtf8(""))
        self.exposure_auto_comboBox.addItem(_fromUtf8(""))
        self.exposure_auto_comboBox.addItem(_fromUtf8(""))
        self.exposure_auto_comboBox.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.exposure_auto_comboBox)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_10 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_12.addWidget(self.label_10)
        self.label_24 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_12.addWidget(self.label_24)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.exposure_absolute_horizontalSlider = QtGui.QSlider(self.horizontalLayoutWidget_2)
        self.exposure_absolute_horizontalSlider.setMinimum(3)
        self.exposure_absolute_horizontalSlider.setMaximum(2047)
        self.exposure_absolute_horizontalSlider.setProperty("value", 250)
        self.exposure_absolute_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.exposure_absolute_horizontalSlider.setObjectName(_fromUtf8("exposure_absolute_horizontalSlider"))
        self.verticalLayout_5.addWidget(self.exposure_absolute_horizontalSlider)
        self.exposure_auto_priority_checkBox = QtGui.QCheckBox(self.horizontalLayoutWidget_2)
        self.exposure_auto_priority_checkBox.setObjectName(_fromUtf8("exposure_auto_priority_checkBox"))
        self.verticalLayout_5.addWidget(self.exposure_auto_priority_checkBox)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_11 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_13.addWidget(self.label_11)
        self.label_25 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_13.addWidget(self.label_25)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.focus_absolute_horizontalSlider = QtGui.QSlider(self.horizontalLayoutWidget_2)
        self.focus_absolute_horizontalSlider.setMaximum(250)
        self.focus_absolute_horizontalSlider.setSingleStep(5)
        self.focus_absolute_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.focus_absolute_horizontalSlider.setObjectName(_fromUtf8("focus_absolute_horizontalSlider"))
        self.verticalLayout_5.addWidget(self.focus_absolute_horizontalSlider)
        self.focus_auto_checkBox = QtGui.QCheckBox(self.horizontalLayoutWidget_2)
        self.focus_auto_checkBox.setChecked(True)
        self.focus_auto_checkBox.setObjectName(_fromUtf8("focus_auto_checkBox"))
        self.verticalLayout_5.addWidget(self.focus_auto_checkBox)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_12 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_7.addWidget(self.label_12)
        self.label_19 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_7.addWidget(self.label_19)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.zoom_absolute_horizontalSlider = QtGui.QSlider(self.horizontalLayoutWidget_2)
        self.zoom_absolute_horizontalSlider.setMinimum(100)
        self.zoom_absolute_horizontalSlider.setMaximum(500)
        self.zoom_absolute_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.zoom_absolute_horizontalSlider.setObjectName(_fromUtf8("zoom_absolute_horizontalSlider"))
        self.verticalLayout_5.addWidget(self.zoom_absolute_horizontalSlider)
        self.label_13 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_5.addWidget(self.label_13)
        self.led1_mode_comboBox = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.led1_mode_comboBox.setObjectName(_fromUtf8("led1_mode_comboBox"))
        self.led1_mode_comboBox.addItem(_fromUtf8(""))
        self.led1_mode_comboBox.addItem(_fromUtf8(""))
        self.led1_mode_comboBox.addItem(_fromUtf8(""))
        self.led1_mode_comboBox.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.led1_mode_comboBox)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_14 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_15.addWidget(self.label_14)
        self.label_27 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_15.addWidget(self.label_27)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.led_frequency_horizontalSlider = QtGui.QSlider(self.horizontalLayoutWidget_2)
        self.led_frequency_horizontalSlider.setMaximum(255)
        self.led_frequency_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.led_frequency_horizontalSlider.setObjectName(_fromUtf8("led_frequency_horizontalSlider"))
        self.verticalLayout_5.addWidget(self.led_frequency_horizontalSlider)
        self.save_camera_setting_pushButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.save_camera_setting_pushButton.setObjectName(_fromUtf8("save_camera_setting_pushButton"))
        self.verticalLayout_5.addWidget(self.save_camera_setting_pushButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.tab_2)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 0, 481, 541))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.display_thresholded_image_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.display_thresholded_image_pushButton.setObjectName(_fromUtf8("display_thresholded_image_pushButton"))
        self.verticalLayout_7.addWidget(self.display_thresholded_image_pushButton)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_28 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout.addWidget(self.label_28)
        self.select_color_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_5)
        self.select_color_comboBox.setObjectName(_fromUtf8("select_color_comboBox"))
        self.select_color_comboBox.addItem(_fromUtf8(""))
        self.select_color_comboBox.addItem(_fromUtf8(""))
        self.select_color_comboBox.addItem(_fromUtf8(""))
        self.select_color_comboBox.addItem(_fromUtf8(""))
        self.select_color_comboBox.addItem(_fromUtf8(""))
        self.select_color_comboBox.addItem(_fromUtf8(""))
        self.select_color_comboBox.addItem(_fromUtf8(""))
        self.select_color_comboBox.addItem(_fromUtf8(""))
        self.select_color_comboBox.addItem(_fromUtf8(""))
        self.select_color_comboBox.addItem(_fromUtf8(""))
        self.select_color_comboBox.addItem(_fromUtf8(""))
        self.select_color_comboBox.addItem(_fromUtf8(""))
        self.select_color_comboBox.addItem(_fromUtf8(""))
        self.select_color_comboBox.addItem(_fromUtf8(""))
        self.select_color_comboBox.addItem(_fromUtf8(""))
        self.select_color_comboBox.addItem(_fromUtf8(""))
        self.select_color_comboBox.addItem(_fromUtf8(""))
        self.select_color_comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.select_color_comboBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_29 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_19.addWidget(self.label_29)
        self.label_30 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_19.addWidget(self.label_30)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.h_min_horizontalSlider = QtGui.QSlider(self.verticalLayoutWidget_5)
        self.h_min_horizontalSlider.setMaximum(255)
        self.h_min_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.h_min_horizontalSlider.setObjectName(_fromUtf8("h_min_horizontalSlider"))
        self.verticalLayout_6.addWidget(self.h_min_horizontalSlider)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_33 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_22.addWidget(self.label_33)
        self.label_34 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_22.addWidget(self.label_34)
        self.verticalLayout_6.addLayout(self.horizontalLayout_22)
        self.s_min_horizontalSlider = QtGui.QSlider(self.verticalLayoutWidget_5)
        self.s_min_horizontalSlider.setMaximum(255)
        self.s_min_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.s_min_horizontalSlider.setObjectName(_fromUtf8("s_min_horizontalSlider"))
        self.verticalLayout_6.addWidget(self.s_min_horizontalSlider)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_39 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.horizontalLayout_25.addWidget(self.label_39)
        self.label_40 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_25.addWidget(self.label_40)
        self.verticalLayout_6.addLayout(self.horizontalLayout_25)
        self.v_min_horizontalSlider = QtGui.QSlider(self.verticalLayoutWidget_5)
        self.v_min_horizontalSlider.setMaximum(255)
        self.v_min_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.v_min_horizontalSlider.setObjectName(_fromUtf8("v_min_horizontalSlider"))
        self.verticalLayout_6.addWidget(self.v_min_horizontalSlider)
        self.load_color_setting_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.load_color_setting_pushButton.setObjectName(_fromUtf8("load_color_setting_pushButton"))
        self.verticalLayout_6.addWidget(self.load_color_setting_pushButton)
        self.horizontalLayout_18.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.add_color_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.add_color_pushButton.setObjectName(_fromUtf8("add_color_pushButton"))
        self.horizontalLayout_21.addWidget(self.add_color_pushButton)
        self.delete_color_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.delete_color_pushButton.setObjectName(_fromUtf8("delete_color_pushButton"))
        self.horizontalLayout_21.addWidget(self.delete_color_pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_31 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_20.addWidget(self.label_31)
        self.label_32 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_20.addWidget(self.label_32)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.h_max_horizontalSlider = QtGui.QSlider(self.verticalLayoutWidget_5)
        self.h_max_horizontalSlider.setMaximum(255)
        self.h_max_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.h_max_horizontalSlider.setObjectName(_fromUtf8("h_max_horizontalSlider"))
        self.verticalLayout_4.addWidget(self.h_max_horizontalSlider)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_35 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_23.addWidget(self.label_35)
        self.label_36 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_23.addWidget(self.label_36)
        self.verticalLayout_4.addLayout(self.horizontalLayout_23)
        self.s_max_horizontalSlider = QtGui.QSlider(self.verticalLayoutWidget_5)
        self.s_max_horizontalSlider.setMaximum(255)
        self.s_max_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.s_max_horizontalSlider.setObjectName(_fromUtf8("s_max_horizontalSlider"))
        self.verticalLayout_4.addWidget(self.s_max_horizontalSlider)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_37 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_24.addWidget(self.label_37)
        self.label_38 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_24.addWidget(self.label_38)
        self.verticalLayout_4.addLayout(self.horizontalLayout_24)
        self.v_max_horizontalSlider = QtGui.QSlider(self.verticalLayoutWidget_5)
        self.v_max_horizontalSlider.setMaximum(255)
        self.v_max_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.v_max_horizontalSlider.setObjectName(_fromUtf8("v_max_horizontalSlider"))
        self.verticalLayout_4.addWidget(self.v_max_horizontalSlider)
        self.save_color_setting_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.save_color_setting_pushButton.setObjectName(_fromUtf8("save_color_setting_pushButton"))
        self.verticalLayout_4.addWidget(self.save_color_setting_pushButton)
        self.horizontalLayout_18.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_17 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_16.addWidget(self.label_17)
        self.label_26 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_16.addWidget(self.label_26)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.device_port_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.device_port_comboBox.setObjectName(_fromUtf8("device_port_comboBox"))
        self.horizontalLayout_14.addWidget(self.device_port_comboBox)
        self.camera_model_comboBox = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.camera_model_comboBox.setObjectName(_fromUtf8("camera_model_comboBox"))
        self.camera_model_comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_14.addWidget(self.camera_model_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.connect_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.connect_pushButton.setObjectName(_fromUtf8("connect_pushButton"))
        self.horizontalLayout_3.addWidget(self.connect_pushButton)
        self.reset_camera_setting_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.reset_camera_setting_pushButton.setObjectName(_fromUtf8("reset_camera_setting_pushButton"))
        self.horizontalLayout_3.addWidget(self.reset_camera_setting_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 514, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionLoad)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.brightness_horizontalSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.label_15.setNum)
        QtCore.QObject.connect(self.contrast_horizontalSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.label_16.setNum)
        QtCore.QObject.connect(self.saturation_horizontalSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.label_18.setNum)
        QtCore.QObject.connect(self.gain_horizontalSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.label_20.setNum)
        QtCore.QObject.connect(self.white_balance_temperature_horizontalSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.label_21.setNum)
        QtCore.QObject.connect(self.sharpness_horizontalSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.label_22.setNum)
        QtCore.QObject.connect(self.backlight_compensation_horizontalSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.label_23.setNum)
        QtCore.QObject.connect(self.exposure_absolute_horizontalSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.label_24.setNum)
        QtCore.QObject.connect(self.focus_absolute_horizontalSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.label_25.setNum)
        QtCore.QObject.connect(self.zoom_absolute_horizontalSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.label_19.setNum)
        QtCore.QObject.connect(self.led_frequency_horizontalSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.label_27.setNum)
        QtCore.QObject.connect(self.h_min_horizontalSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.label_30.setNum)
        QtCore.QObject.connect(self.s_min_horizontalSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.label_34.setNum)
        QtCore.QObject.connect(self.v_min_horizontalSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.label_40.setNum)
        QtCore.QObject.connect(self.h_max_horizontalSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.label_32.setNum)
        QtCore.QObject.connect(self.s_max_horizontalSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.label_36.setNum)
        QtCore.QObject.connect(self.v_max_horizontalSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.label_38.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Brightness", None))
        self.label_15.setText(_translate("MainWindow", "0", None))
        self.label_2.setText(_translate("MainWindow", "Contrast", None))
        self.label_16.setText(_translate("MainWindow", "0", None))
        self.label_3.setText(_translate("MainWindow", "Saturation", None))
        self.label_18.setText(_translate("MainWindow", "0", None))
        self.label_4.setText(_translate("MainWindow", "Gain", None))
        self.label_20.setText(_translate("MainWindow", "0", None))
        self.label_5.setText(_translate("MainWindow", "Power Line Frequency", None))
        self.power_line_frequency_comboBox.setItemText(0, _translate("MainWindow", "2", None))
        self.power_line_frequency_comboBox.setItemText(1, _translate("MainWindow", "1", None))
        self.power_line_frequency_comboBox.setItemText(2, _translate("MainWindow", "0", None))
        self.white_balance_temperature_auto_checkBox.setText(_translate("MainWindow", "White Balance Auto", None))
        self.label_6.setText(_translate("MainWindow", "White Balance", None))
        self.label_21.setText(_translate("MainWindow", "0", None))
        self.label_7.setText(_translate("MainWindow", "Sharpness", None))
        self.label_22.setText(_translate("MainWindow", "0", None))
        self.load_camera_setting_pushButton.setText(_translate("MainWindow", "Load", None))
        self.label_8.setText(_translate("MainWindow", "Backlight Compensate", None))
        self.label_23.setText(_translate("MainWindow", "0", None))
        self.label_9.setText(_translate("MainWindow", "Exposure Auto", None))
        self.exposure_auto_comboBox.setItemText(0, _translate("MainWindow", "3", None))
        self.exposure_auto_comboBox.setItemText(1, _translate("MainWindow", "2", None))
        self.exposure_auto_comboBox.setItemText(2, _translate("MainWindow", "1", None))
        self.exposure_auto_comboBox.setItemText(3, _translate("MainWindow", "0", None))
        self.label_10.setText(_translate("MainWindow", "Exposure Absolute", None))
        self.label_24.setText(_translate("MainWindow", "0", None))
        self.exposure_auto_priority_checkBox.setText(_translate("MainWindow", "Exposure Auto Priority", None))
        self.label_11.setText(_translate("MainWindow", "Focus Absolute", None))
        self.label_25.setText(_translate("MainWindow", "0", None))
        self.focus_auto_checkBox.setText(_translate("MainWindow", "Focus Auto", None))
        self.label_12.setText(_translate("MainWindow", "Zoom Absolute", None))
        self.label_19.setText(_translate("MainWindow", "0", None))
        self.label_13.setText(_translate("MainWindow", "LED Mode", None))
        self.led1_mode_comboBox.setItemText(0, _translate("MainWindow", "0", None))
        self.led1_mode_comboBox.setItemText(1, _translate("MainWindow", "1", None))
        self.led1_mode_comboBox.setItemText(2, _translate("MainWindow", "2", None))
        self.led1_mode_comboBox.setItemText(3, _translate("MainWindow", "3", None))
        self.label_14.setText(_translate("MainWindow", "LED Frequency", None))
        self.label_27.setText(_translate("MainWindow", "0", None))
        self.save_camera_setting_pushButton.setText(_translate("MainWindow", "save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Camera", None))
        self.display_thresholded_image_pushButton.setText(_translate("MainWindow", "Display Thresholded Image", None))
        self.label_28.setText(_translate("MainWindow", "Select Color :", None))
        self.select_color_comboBox.setItemText(0, _translate("MainWindow", "All", None))
        self.select_color_comboBox.setItemText(1, _translate("MainWindow", "black", None))
        self.select_color_comboBox.setItemText(2, _translate("MainWindow", "blue", None))
        self.select_color_comboBox.setItemText(3, _translate("MainWindow", "brown", None))
        self.select_color_comboBox.setItemText(4, _translate("MainWindow", "cyan", None))
        self.select_color_comboBox.setItemText(5, _translate("MainWindow", "gray", None))
        self.select_color_comboBox.setItemText(6, _translate("MainWindow", "green", None))
        self.select_color_comboBox.setItemText(7, _translate("MainWindow", "magenta", None))
        self.select_color_comboBox.setItemText(8, _translate("MainWindow", "orange", None))
        self.select_color_comboBox.setItemText(9, _translate("MainWindow", "pink", None))
        self.select_color_comboBox.setItemText(10, _translate("MainWindow", "red", None))
        self.select_color_comboBox.setItemText(11, _translate("MainWindow", "white", None))
        self.select_color_comboBox.setItemText(12, _translate("MainWindow", "yellow", None))
        self.select_color_comboBox.setItemText(13, _translate("MainWindow", "color1", None))
        self.select_color_comboBox.setItemText(14, _translate("MainWindow", "color2", None))
        self.select_color_comboBox.setItemText(15, _translate("MainWindow", "color3", None))
        self.select_color_comboBox.setItemText(16, _translate("MainWindow", "color4", None))
        self.select_color_comboBox.setItemText(17, _translate("MainWindow", "color5", None))
        self.label_29.setText(_translate("MainWindow", "H Min", None))
        self.label_30.setText(_translate("MainWindow", "0", None))
        self.label_33.setText(_translate("MainWindow", "S Min", None))
        self.label_34.setText(_translate("MainWindow", "0", None))
        self.label_39.setText(_translate("MainWindow", "V Min", None))
        self.label_40.setText(_translate("MainWindow", "0", None))
        self.load_color_setting_pushButton.setText(_translate("MainWindow", "Load", None))
        self.add_color_pushButton.setText(_translate("MainWindow", "Add", None))
        self.delete_color_pushButton.setText(_translate("MainWindow", "Delete", None))
        self.label_31.setText(_translate("MainWindow", "H Max", None))
        self.label_32.setText(_translate("MainWindow", "0", None))
        self.label_35.setText(_translate("MainWindow", "S Max", None))
        self.label_36.setText(_translate("MainWindow", "0", None))
        self.label_37.setText(_translate("MainWindow", "V Max", None))
        self.label_38.setText(_translate("MainWindow", "0", None))
        self.save_color_setting_pushButton.setText(_translate("MainWindow", "save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Color", None))
        self.label_17.setText(_translate("MainWindow", "Device Port", None))
        self.label_26.setText(_translate("MainWindow", "Camera Model", None))
        self.camera_model_comboBox.setItemText(0, _translate("MainWindow", "Logitech c920", None))
        self.connect_pushButton.setText(_translate("MainWindow", "Connect", None))
        self.reset_camera_setting_pushButton.setText(_translate("MainWindow", "Reset Cam Setting", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave_As.setText(_translate("MainWindow", "Save As", None))
        self.actionLoad.setText(_translate("MainWindow", "Load", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

